### PR TITLE
#159965485 Users should be able to like and or dislike articles.

### PR DESCRIPTION
**Pull request by ghost**
## What does this PR do?
```
Add the functionality to like or dislike articles
```

## Description of Task to be completed?
```
- Enable user to like an article 
- Enable user to dislike an article
```

## How should this be manually tested?
```
1. Clone the repository
2. Check out the branch ft-like-dislike-articles-159965485
3. Run the command ` coverage run --source=authors/apps manage.py test && coverage report -m`
```
## Any background context you want to provide?

```
Let us appreciate those authors who go out of their way to create good content with a Like and encourage those authors who do not meet our expectations with a dislike.

```

## What are the relevant pivotal tracker stories?

[#159965485](https://www.pivotaltracker.com/story/show/159965485)

## Screenshots

Like articles
like articles

Dislike articles
dislike articles copy

Unlike articles
unlike articles

Undislike articles
undislike articles

Dislike then like articles
dislike to like articles

Like then dislike articles
like to dislike article

## Questions:

```
Was this PR helpful ???

```

### CODE REVIEW

**Comment by DerKip** [comment]
@rethes  why has the coverage decreased?

**Review by Teddykavooh — COMMENTED** [review]
Good linting

**Comment by ghost** [comment]
@DerKip I added new files that are not being tested to the .coveragerc

**Review by Derrickkip — APPROVED** [review]
Good implementation

**Comment by DerKip** [comment]
@rethes legit.

**Review by Teddykavooh — APPROVED** [review]

**Review by DerKip — APPROVED** [review]

**Review by WNjihia — APPROVED** [review]

**Pull request merged**
