### PR TITLE
#159965487 Users can favorite articles 

### PR DESCRIPTION
**Pull request by DerKip**
## What does this PR do?
```
This PR enables an authenticated user to favourite an article. It also shows
how many people have favourited an article 
```
## Description of Task to be completed?
```
- Write unit tests for favouriting an article
- Update The profile model by adding the favourited field
- Create an endpoint for favouriting an article  ArticlesFavoriteAPIView
```
## How should this be manually tested?

- Checkout ```ft-favorite-articles-159965487``` branch
- Run migrations ```$python manage.py migrate```
- Run the server ```$python manage.py runserver```
- Fire up postman and send a POST request to ```http://127.0.0.1:8000/api/articles``` to create an article 
```{
  "article": {
    "title": "How to eat fast",
    "description": "Ever wonder how?",
    "body": "You have to believe",
    "tagList": ["nuts", "meat", "pie"]
  }
}
```
- Then send a POST request to ```http://127.0.0.1:8000/api/articles/how-to-eat-fast/favorite```
the article's ```favorited``` field will be updated to ```True``` and the ```favoritedcount``` be 1(this keeps on adding when a user favorites an article )
- To unfavorite the article, send  a DELETE request to the favorite article endpoint ```http://127.0.0.1:8000/api/articles/:slug/favorite```, It throws an exception if the ```:slug``` is non-existent.

- When a user retrieves all articles by sending a  GET request to this endpoint ```http://127.0.0.1:8000/api/articles``` 
The favorited field will be False for all articles if a user isn't authenticated, but if a user is authenticated, It'll  be True if he/she has favorited an article and vice versa.

## What are the relevant pivotal tracker stories?

[#159965487](https://www.pivotaltracker.com/n/projects/2192365/stories/159965487)

## Screenshots if available to support PR.

**Favoriting an article**
screen shot 2018-09-13 at 20 22 52

**Unfavoriting an article**
screen shot 2018-09-16 at 19 23 36

**All Articles**
screen shot 2018-09-13 at 20 20 25

### CODE REVIEW

**Review by Mutuba — DISMISSED** [review]
Nice implementation and well tested!

**Review by Quantum-35 — DISMISSED** [review]
LGTM

**Comment by WNjihia** [comment]
@DerKip Do you mind clarifying how unfavoriting an article works?

**Comment by WNjihia** [comment]
Also kindly resolve the merge conflicts

**Comment by DerKip** [comment]
@WNjihia, One unfavorites an article after sending a DELETE request to the favorite article endpoint ```http://127.0.0.1:8000/api/articles/:slug/favorite```, It throws an exception if the ```:slug``` is non-existent 

 I've created a util method in the Profile model that removes the article from the favorites field.
screen shot 2018-09-13 at 23 17 32
This method is called in the ArticlesFavoriteAPIView's delete method 
screen shot 2018-09-13 at 23 20 34

**Comment by DerKip** [comment]
@WNjihia, I'm working on the merge conflics

**Review by Derrickkip — DISMISSED** [review]
Looks Good to Me

**Review by Mutuba — APPROVED** [review]

**Review by Derrickkip — APPROVED** [review]

**Review by Teddykavooh — APPROVED** [review]
Job well done.

**Pull request merged**
