### PR TITLE
#159965478  User reset the password via email

### PR DESCRIPTION
**Pull request by Quantum-35**
## What does this PR do?
```
Allows a user to reset their password by entering their email and a reset
 token is sent to the user's email.
```

## Description of Task to be completed?
```
Implemented a forgot password View that allows a user to enter their email which 
sends a reset token to their respective email. Then the reset password View decodes
 the token and checks if it is valid and update users password in the database.
```

## Tools 
```
- RabbitMQ - to install on Mac run  brew install rabbitmq

```

## How should this be manually tested?

```
- Clone this repo and pip install requirements.txt
- run celery worker using command   celery -A authors worker -l info
- Create a virtual environment, start it and run ./manage.py runserver
- Navigate to postman register, confirm your account by checking your email 
   and clicking the confirmation link
- Go to forgot password url (http://127.0.0.1:8000/api/users/reset_password/), 
      Enter your email and send. A password reset link will be sent to your 
      email with the reset token
- Navigate to (http://127.0.0.1:8000/api/users/reset_password/) Enter your email,
       reset token and your new password.

```

## What are the relevant pivotal tracker stories?

[#159965478](https://www.pivotaltracker.com/story/show/159965478)

## Screenshots if available to support PR.

screen shot 2018-09-10 at 18 36 52

## Questions:

```
Was this PR helpful?

```

### CODE REVIEW

**Comment by Quantum-35** [comment]
Please Review my PR @DerKip @Derrickkip @rethes @Teddykavooh @WNjihia

**Comment by Quantum-35** [comment]
I have resolved the merge conflicts. Please review my PR @DerKip @DerKip @rethes @WNjihia

**Review by Derrickkip — DISMISSED** [review]

**Comment by ghost** [comment]
@Quantum-35 Looks good to me

**Review by DerKip — DISMISSED** [review]
LGTM

**Review by Derrickkip — DISMISSED** [review]
Good implementation

**Review by DerKip — DISMISSED** [review]

**Review by Derrickkip — DISMISSED** [review]

**Review by Teddykavooh — DISMISSED** [review]
Nice work. Doc strings are in: """..."""

**Review by Derrickkip — APPROVED** [review]

**Review by Teddykavooh — APPROVED** [review]
LGTM

**Review by WNjihia — APPROVED** [review]

**Pull request merged**
