### PR TITLE
#159965475 Users should receive a JWT

### PR DESCRIPTION
**Pull request by DerKip**
## What does this PR do?

This PR allows a user to receive a JWT once registered successfully via the registration endpoint or logs in via the login endpoint.

## Description of tasks to be completed
- Create unittests for the login and registartion endpoints to test if a user recieves at token.
- Create a ```generate_token``` functioin
- Append the token on the payload  after successful login and registartion
## How should this be manually tested?

- Clone the repo.
- Checkout  ft-jwt-authentication-159965475. 
- Create db and make migrations.
- Fire up the server ```$python manage.py``` runserver
- Start postman and test the login and registratioin endpoints
  ```http://127.0.0.1:8000/api/users/login/```
```http://127.0.0.1:8000/api/users/```

## Relevant PT story

[#159965475](https://www.pivotaltracker.com/n/projects/2192365/stories/159965475)

### CODE REVIEW

**Review by Teddykavooh — DISMISSED** [review]
Commendable work.

**Review by Quantum-35 — DISMISSED** [review]

**Review by Derrickkip — DISMISSED** [review]
The implementation looks good to me

**Review by Mutuba — DISMISSED** [review]
I like the implementation. I have tested it works!

**Review by Quantum-35 — DISMISSED** [review]

**Review by Derrickkip — APPROVED** [review]
Looks Good To Me

**Review by Quantum-35 — APPROVED** [review]

**Review by WNjihia — APPROVED** [review]

**Pull request merged**
