### PR TITLE
#159965469 Integrate TravisCI with readme badge

### PR DESCRIPTION
**Pull request by Quantum-35**
#### What does this PR do?
Add Travis CI build badge to README.
#### Description of Task to be completed?
Add tests so that TravisCI can successfully build. 
#### What are the relevant pivotal tracker stories?
[#159965469](https://www.pivotaltracker.com/story/show/159965469)
#### Here is a  Screenshot
readme

### CODE REVIEW

**Review by Derrickkip — COMMENTED** [review]
There is no badge @Quantum-35, only a changed .gitignore file

**Comment by Quantum-35** [comment]
@Derrickkip I added the TravisCI badge on the readme but it has not updated in the PR, but it is there in the readme

**Comment by Mutuba** [comment]
You can do better by adding more colour!

**Comment by Quantum-35** [comment]
@Mutuba Your comment is not Specific.

**Comment by kipropbrian** [comment]
Your PR naming is not correct.

**Comment by Quantum-35** [comment]
Fixed it @kipropbrian

**Review by Teddykavooh — COMMENTED** [review]
Commendable work.

**Review by WNjihia — APPROVED** [review]

**Pull request merged**
