### PR TITLE
#59965471 Deploy App to Heroku

### PR DESCRIPTION
**Pull request by DerKip**
## What does this PR do?
```
Configures the app allowing it to be deployed to Heroku.

```

## Description of Task to be completed?
```
- Create procfile 
- $ pip install gunicorn 
- Create runtime file 

```
## How should this be manually tested?

```
- Checkout  ch-deploy-159965471 
- Install the requirements
-  open terminal and run -> gunicorn authors.wsgi

```
## What are the relevant pivotal tracker stories?

[#159965471](https://www.pivotaltracker.com/story/show/159965471)

### CODE REVIEW

**Review by Derrickkip — APPROVED** [review]

**Review by Derrickkip — DISMISSED** [review]
LGTM

**Review by Quantum-35 — DISMISSED** [review]
Looks good to me

**Comment by ghost** [comment]
it is okay.

**Comment by WNjihia** [comment]
@DerKip  kindly separate requirements used to run the app vs requirements used for development. Those for development should be in `requirements-dev.txt`. Also kindly resolve merge conflicts

**Review by WNjihia — APPROVED** [review]

**Pull request merged**
